services:
  fastapi:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${HOST}
  mongodb:
    image: mongo:latest
    ports:
      - 27017
    volumes:
      - /bitnami/mongodb
